#ifndef CPPPROJECTSTRUCTUREUSINGCMAKE_FORMULA_H
#define CPPPROJECTSTRUCTUREUSINGCMAKE_FORMULA_H

class Formula
{
public:
    static int bla(int arg1);
};

#endif //CPPPROJECTSTRUCTUREUSINGCMAKE_FORMULA_H